[package]
org = "hansaninissanka"
name = "order_server"
version = "0.1.0"
distribution = "2201.9.0"

[build-options]
observabilityIncluded = true
cloud = "k8s"
platform = "choreo"
ballerinaVersion = "2201.9.0"